### ISSUE TITLE
Parameter Identification: cannot find `Partition coefficient (water/container)`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1007]
I cannot find the parameter `Partition coefficient (water/container)` in the list of parameters available for parameter identification. I would expect to find all parameter values in MoBi.

**Comment by Yuri05** [comment]
I guess it's because those parameters are defined as "CanBeVaried=false" in PK-Sim.
Unfortunately, MoBi does not allow to change the flag currently.

As a workaround:
* Save your spatial structure to pkml
* Text edit replace `flag="52"` with `flag="38"`
* Load changed spatial structure in PKML
* Reconfigure your simulations and replace the original spatial structure with the changed one
Then you can optimize the paramters in advanced mode

![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/398724d7-2990-4f56-a212-f7eb39260118)

**Comment by Yuri05** [comment]
Question: isn't it sufficient to vary the **accessible** partition coeffs?
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/416b856b-0350-48ea-bc48-baa827b62c00)

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/MoBi/issues/294

**Comment by PavelBal** [comment]
> Question: isn't it sufficient to vary the accessible partition coeffs?

I have created a custom parameter in a new container by copying the `Partition coefficient (water/container)` and then wanted to fit it... Well I guess it will be solved if issue #294 is solved.
