### ISSUE TITLE
Do not show warnings for observers and dimensions by default

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1098]
Set these settings to "off" by default:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/fa1ba933-8a6d-4a70-9248-d490d6220d15)

 As it turned out, this is quite expensive during simulation creation.

Additionally, better explanation in the documentation should be added.

**Comment by msevestre** [comment]
>As it turned out, this is quite expensive during simulation creation.

@rwmcintosh @PavelBal 
Is the validation expensive or the display expensive ?

**Comment by rwmcintosh** [comment]
At this point, it seems like it's the creation of the messages. Specifically finding the appropriate building block from the project.

**Comment by rwmcintosh** [comment]
We had good success with improving the performance of the message creation last week. Do you still think this is necessary @PavelBal?

I think if it's only because it took a long time to create messages (if there were a lot) then we don't need this anymore.

If it's for a better reason, we can keep it.

**Comment by PavelBal** [comment]
Was only for performance reasons. Well done, closing.
