### ISSUE TITLE
Renaming an entity should only "Rename also" within the module

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1154]
- [x] Improve the title of "Rename also..."
- [x] It should also rename neighborhoods (names of the neighborhoods, not only the paths).
- [x] Also rename tags of all entities in the module

**Comment by PavelBal** [comment]
- [ ] Improve the title of "Rename also..."
- [ ] It should also rename neighborhoods (names of the neighborhoods, not only the paths).

**Comment by rwmcintosh** [comment]
I think the two main subtasks are already implemented by other things we've done since this issue was raised.

I changed the name of 'Stomach' to 'Tummy'
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/b701b873-5151-4272-9b70-2688aa309c17)

Tags are updated
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/09f31c5a-80bb-42b9-a107-95670d4add2b)

Neighborhoods updated both in name and path
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/f4285068-07c4-481d-8663-72db1d227add)

@PavelBal can you confirm this is what is expected? Or was there something else I'm missing?

**Comment by msevestre** [comment]
Does it rename ONLY in the module or the whole project?

We want module only I believe? At least from the title

**Comment by rwmcintosh** [comment]
Yeah, that part isn't done. Limiting to the module. But the tags and neighborhoods seems done

**Comment by rwmcintosh** [comment]
Does it make sense to allow an option to rename in other modules?

Default select everything in the current module, but allow the user to select from other modules too?

**Comment by msevestre** [comment]
yes tags etc..were done in other PR I made with renaming of neighborhoods

>Default select everything in the current module, but allow the user to select from other modules too?

why not but this should not be the default option

**Comment by msevestre** [comment]
not even sure it would work with renaming an organ used in other neighbourhoods in another module 
Say Stomach =>tummy 
Stomch used in Module2.
Are neighborhoods going to be removed also in module 2. not sure.

**Comment by PavelBal** [comment]
I would say only in the module.

**Comment by rwmcintosh** [comment]
Ok, just going to change the title, and limit the affected building blocks to the module.
