### ISSUE TITLE
Default PSV contains too many entries

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#118]
When MoBi creates a  `Parameter Start Value BuildingBlock` (or short `PSV`),  for a given `Spatial Structure` and `Molecules BuildingBlock`, a lot of `Parameter Start Value` entries are being created automatically:

 * one entry for each parameter of the associated `Spatial Structure`
 * one for each global molecule parameters
 * one for each local parameter in **EACH** `physical` container of the associated `Spatial Structure`

All these entries create a lot of noise as they simply duplicate the default value that was defined either in the `Spatial Structure` or in the `Molecule BuildingBlock`.

My suggestion would be by default to **NOT**  generate any entries in the PSV. It would be then very easy for the user to see at one glance **WHICH** parameters have changed from default. Also it would make the concept of PSV much easier to understand for new users.

PK-Sim would then only generate PSV entries that differs from the default value.

_EDIT:_ ~~The same goes for `MSV`.~~ MSV is a different beast and should be left as is

What do you guys think?

I'd like to get some user feedback on that.

**Comment by UlrichSi** [comment]
That would be fine for me, although we do have the option to select "Show only changed values" or "Show only new values" to filter out the noise. Some thoughts:
1. For MSV, an entry must also be created whenever there is a scale divisor <> 1 present. 
2. It should also be possible to override Reaction and all other BB parameters here.
3. How will changes in the simulation be written back to the BBs? Will the current logic remain, i.e., a changed parameter value will show up in the PSV? Meaning that a new PSV entry will be created at this particular moment?

**Comment by PavelBal** [comment]
I support the idea of making PSV/MSV-BBs leaner. For PSV:

1) It is a good idea to generate only entries for changed values. It this case, an easy way to create entries manually should be intorduced, e.g. using the parameters-tree as in a formula-dialogue (e.g. a button "Create new entry" which opens a parameters-tree where the user will select a parameter she/he wants to change).
2) A huge flood of entries in the PSV is currently generated by the "Relative expression" concept. This is a very inconvenient concept of setting starting values for proteins and I would prefer to somehow merge it with the MSV-BB (e.g., as an additional PSV-BB linked to a MSV-BB only for expression values).
3) Same question as @UlrichSi. I favor the concept of commiting any changes to the PSV. To stress it - ANY parameter change, except for the events-parameters (these are often changed and SHOULD NOT be a part of a PSV), should be commited to the PSV. Right now, the behavior is very inconsistent - some parameters are commited to PSV, some to reactions-BB, some to spatial structure-BB (e.g. GFR_spec). A clear separation between model structure and parametrization is easier to handle, I think,

For MSV, I am not sure whether the default MSV should be emtpy. MSV-BB defines where the molecules are present, and it is often useful to see which molecule is present where in order to check where the reactions are created.

**Comment by msevestre** [comment]
Thanks for the comments. I agree after reading this, that the suggestion to make the start values leaner really only applies to PSV. I am going to Edit the question

**Comment by msevestre** [comment]
>It should also be possible to override Reaction and all other BB parameters here

I think it implicitly works at the moment. If a psv is defined for a reaction parameter, it will be used.... but I may be wrong here 

>How will changes in the simulation be written back to the BBs? [...]Meaning that a new PSV entry will be created at this particular moment?

YES

>It is a good idea to generate only entries for changed values. It this case, an easy way to create entries manually should be intorduced, e.g. using the parameters-tree as in a formula-dialogue

I like the idea. This would reuse some existing concepts. For more experienced users, direct input would still be possible

>Relative Expression

This is another beast altogether. There is definitely some improvement that can be made here. I am really looking at trying to remove the noise

> Update/Commit logic
If there is a need to change once again the update/commit logic, this should be discussed in another thread :)

**Comment by UlrichSi** [comment]
>> It should also be possible to override Reaction and all other BB parameters here

> I think it implicitly works at the moment. If a psv is defined for a reaction parameter, it will be used.... but I may be wrong here

I haven't tried it but I believe it does, and it should remain that way ;-)

**Comment by Yuri05** [comment]
Think we can close the issue in favor of OSMOSES?

**Comment by PavelBal** [comment]
Yes
