### ISSUE TITLE
Extend Parameter Values

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1226]
@PavelBal 

Somehow we have to extend expression profiles in new Parameter values for new containers added by a module

**Comment by PavelBal** [comment]
Additionally - extend for all local molecule parameters.

**Comment by PavelBal** [comment]
Discussion on 13.12.2023:

### 1. "Extend" action for the Parameter Values BB (maybe rename to "Add local molecule parameters"?):
- Open a dialog for selection of a spatial structure (from one of the modules) and multi-selection of molecules (same view as for "Extend" of Initial Conditions?):

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/6123ca8d-8de4-466d-9521-8ffe64230aca)

- Adds entries for all *local* molecule parameters in all physical containers (same logic as for "extend" of IC BB) that are described by a *constant formula*.

### 2. Add protein expression
- Open a dialog for selection of **one** organ within the spatial structure of any of the modules and **multiple** proteins from the expression-BB
- Adds entries for the expression parameters of the proteins (formulas and parameters might differ depending on protein type) in the selected organ:
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/9c60152c-b0b2-4503-ae8f-d09c4f01d05e)

**Q: What happens if the user first 1. extends (adds local molecule parameters) and the 2. adds protein expression?**
**A:** "Add local parameters for an enzyme will add local constant parameters "Fraction expressed intracellular", "Initial concentration", and "Relative expression". These parameters are also part of the expression profile I would be overwritten. "Add protein expression" should overwrite these parameters (if already present in the PV BB) but show a warning to the user: "Warning: Following parameters are present in the PV BB and will be overwritten by this action".


@rwmcintosh @Yuri05 @msevestre  Please review and comment. If no comments (objections) - please implement ;)

**Comment by rwmcintosh** [comment]
I separated out item 1 and 2 from the discussion into separate issues and will use this issue # to address protein expressions.

Extend is via #1245

**Comment by rwmcintosh** [comment]
> A: "Add local parameters for an enzyme will add local constant parameters "Fraction expressed intracellular", "Initial concentration", and "Relative expression". These parameters are also part of the expression profile I would be overwritten. "Add protein expression" should overwrite these parameters (if already present in the PV BB) but show a warning to the user: "Warning: Following parameters are present in the PV BB and will be overwritten by this action".

The former and current extend functionality has opted to preserve the existing parameter values (without advising the user), so should we leave this the way it is? We can advise user of the parameter values that **won't** be overwritten rather than **will** be overwritten.

Should this be symmetrical, in other words, if you add expression first, then extend should we advise the user and preserve existing values?

**Comment by PavelBal** [comment]
Yes, if the entries are already in the list, do not overwrite, but inform the user.

**Comment by rwmcintosh** [comment]
> Yes, if the entries are already in the list, do not overwrite, but inform the user.

Only for adding expression? Or should that happen during Extend as well? And also for Initial Conditions?

**Comment by PavelBal** [comment]
OK, sorry, I didn't think about it thoroughly enough. I think the best way would be to show a list of paths that would be overwritten where the user can select which values to overwrite. If such a list would use the same view as the actual view of the parameter values, the user could even filter for path parts.

**Comment by rwmcintosh** [comment]
I see, rather than just an informational view with a list of paths, we use a grid that allows the user to select which will be replaced and which will be retained.

We could use that for all cases like this that are 'Extend' features.
