### ISSUE TITLE
Combining large and small molecules models

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1262]
In a single MoBi project, PK-Sim modules created with the small molecules (SM) and large molecules (LM) structures can co-exist.

- [ ] First of all, it would be cool if the information about the structure could be displayed somewhere.

Now what happens when the user combines the two models?

- [ ] Select SM module first, LM module second - seems not to be a problem, the new simulation correctly describes both molecules.
- [ ] Select LM module first, SM module second -> Simulation cannot be created, because a set of molecule parameters is missing in the neighborhoods between plasma and interstitial:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/8591de4e-d39d-41b8-93a2-4bd7f9700300)

also molecule property `Kd (FcRn) in endosomal space of container` in containers is missing.

Could we check the order and if a SM modules is selected after a LM module, show a warning (but allow to continue)?

**Comment by Yuri05** [comment]
I don't think that combining SM and LM modules makes sense at all.
* LM module is more or less a superset of SM module - theoretically, merging LM over SM would result just in the original LM-Module?
* Merging SM over LM would *remove* some containers in the spatial structure, but keep some protein-specific transports etc. (which would have no effect then because not created in the simulation) and probably some other side effects.

Or are you talking about something like "export an **organ** from SM-Spatial structure and try to import it into LM-spatial structure"?

**Comment by PavelBal** [comment]
> I don't think that combining SM and LM modules makes sense at all.

Well, not necessarily. I can add a LM module to a project based on SM and it seems to work, it only does not work if LM is selected first. So in theory I could combine LM and SM models in MoBi, if I pay attention to the order of module selection.

**Comment by PavelBal** [comment]
Not so important atm.
