### ISSUE TITLE
Selection of parent container path

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1278]
When selecting the parent container of a top-level container of a module:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/01c2474a-5a8f-4066-a7ca-6a4fc9398226)

1. When showing container from the *same* module (here, the "Two-container module"), only show containers that are on parallel branches to the currently selected container. In this case, "Container A" (and all of his descendants, if present) should **not** be shown. Only show "Container B" (and its descendants, if present).
2. ~~[When selecting any container, *prepend* its "parent container path". E.g., "Container A" from "Second module" has the "Organism" container set as parent container. When the user selects "Container A" as the parent container for "Container A" from the "Two-container module" (as currently shown in the screenshot), the path that is created should be "Organism|Container A" (now, its only "Container A").]~~(#1330)
3. ~~[What happens when the user changes the reference container for any container, that is a parent for another? E.g. "Container B" from "Two-container module" is set as a parent to "Container A" in "Second module". The user changes the parent container of "Container A".
  a. **No** automatic changes in parent container paths, no verifications. Easy to implement, but in this case we have to add a message to the user somewhere.
  b. All other paths are adjusted, circular references are checked, sanity checks... Probably too complex to cover all possible use cases. Not V1.]~~(#1393)

**Comment by PavelBal** [comment]
2. is actaully done when creating neighborhoods:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/f1e222b1-0adf-4e43-8dd3-308d61b6a47e)

**Comment by Yuri05** [comment]
@PavelBal please remove from V12 project if not urgent

**Comment by PavelBal** [comment]
At least 

> When selecting any container, prepend its "parent container path". E.g., "Container A" from "Second module" has the "Organism" container set as parent container. When the user selects "Container A" as the parent container for "Container A" from the "Two-container module" (as currently shown in the screenshot), the path that is created should be "Organism|Container A" (now, its only "Container A").

should be part of V1. As is done with neighborhoods.

**Comment by Yuri05** [comment]
@PavelBal ok, can you please extract that part into a separate issue and put that new issue on "accepted in V12" and then remove this issue from V12?

**Comment by rwmcintosh** [comment]
In the attached project find `Third Module` | `Organism` and `Container C`
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/24b99563-b525-4980-bf3a-d19cefb9205d)

Use the ellipsis to specify a parent path
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/b36dc456-c277-4611-9386-4b595e71eb8a)

Pick `Container B` from Second Module
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/0c44f062-33d5-4445-acce-5d46b9e30e73)

The result shows the name only, but it should have `Organism|Container B` instead of `Container B`
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/552d0d21-b8d2-4624-a302-193adc1cb8ca)



[Two-Compartment.zip](https://github.com/user-attachments/files/16020014/Two-Compartment.zip)

**Comment by rwmcintosh** [comment]
I created another separate issue for the list in the description and linked the new issue with the original repot (but struck through).

For V1 we will just make sure that this view does not present the user with a way to choose a parent container reference to itself.
