### ISSUE TITLE
Renaming of an extesion module converts a PK-Sim module to extension module.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1410]
[rename-converts-pksim-to-extension.zip](https://github.com/user-attachments/files/16233219/rename-converts-pksim-to-extension.zip)

In the attached project, ther are two modules:

- PK-Sim module "iv 0.05 mg/kg (2 min)"
- xModule "x"

When I rename the extension module "x", I get the notification "THe PK-Sim module ... will be converted to an extension module" and "iv 0.05 mg/kg (2 min)" becomes an xModule. Why?

**Comment by rwmcintosh** [comment]
This is because of the way we are detecting changes in modules. There are hundreds of change commands that could trigger this conversion and we are not inspecting every one to check if this is or isn't a case that should convert. Instead, we just compare the Module version number when it was imported and if it changes, we say this module isn't 'as-imported'. So, if we think there are some cases that should be excluded, the best would be to not increment the module version.

That might make sense here: Rename is not a reason to increment the module version? It's a totally non-structural change

**Comment by rwmcintosh** [comment]
We should be able to exclude individual commands from converting the module to an extension module.

**Comment by benjaperez1983** [comment]
[rename-converts-pksim-to-extension.zip](https://github.com/user-attachments/files/16471023/rename-converts-pksim-to-extension.zip)
Converted file to open on the latest Mobi

**Comment by PavelBal** [comment]
Hm, true.
