### ISSUE TITLE
Which actions trigger conversion of PK-Sim module to exntesion module?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1429]
Can you list here (find in code) all actions that trigger the conversion of PK-Sim module to an extension module? Now and then I get the notification that the module will be converted to an extension module, while I would not expect it.

**Comment by rwmcintosh** [comment]
Big list.

**Comment by rwmcintosh** [comment]
I don't think I'll list them because there are so many. In short, any change that affects a building block will trigger it.

There are some module level commands that could trigger it too, for example, removing a building block. But I see in another issue that rename is included, although probably should not be.

![image](https://github.com/user-attachments/assets/5a29b657-c760-407b-b6ae-4369fb828830)

**Comment by rwmcintosh** [comment]
Let's close this because we won't create a list. For now, when you find one that should not trigger a conversion, create a new issue and we will close them as they come up.
