### ISSUE TITLE
Adding of reaction parameter to the list of references fails

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1466]
The project here https://github.com/esqLABS/bug-reports/tree/cannot-open-simulation-294 was created with MoBi build 294.

- Open the module "TMDD and clearance"
- Open reaction `Non-competitive NTCP transporter inhibition1`
- Try to add parameter `relativeNTCPChange` to the list of references:

![image](https://github.com/user-attachments/assets/c6b9d310-2c6d-4021-99e7-e6e5fd9a19ca)

Application:
MoBi® 12.0.299

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.refreshDisplayedSimulation(IMoBiSimulation simulation)
   at MoBi.Presentation.Presenter.Main.SimulationExplorerPresenter.Handle(SimulationStatusChangedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

shown like 5 times or so.

**Comment by rwmcintosh** [comment]
This is caused by a previous bug reported
https://github.com/Open-Systems-Pharmacology/MoBi/issues/1464
https://github.com/Open-Systems-Pharmacology/MoBi/issues/1476

Because we had allowed modules to be removed while still in use by simulations, the loading of simulations is stopped when a simulation could not be loaded due to a missing module.

Even though this specific simulation was intact, the simulation did not have a node in the Simulation Explorer window because not all simulations were fully loaded due to the previous error.
