### ISSUE TITLE
Parameter `Allometric scale factor`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1470]
AFAIK this parameter is not used anywhere - why is it there?

**Comment by PavelBal** [comment]
@Yuri05 any insights?

**Comment by Yuri05** [comment]
It is used by the create individual algo.
https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/wiki/Create-Individual-Algorithm#step-2

https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/7dee6e9d0989f5dfec9dd9ce73a1ba15a751a839/src/PKSim.Core/Services/CreateIndividualAlgorithm.cs#L420-L431

**Comment by PavelBal** [comment]
Ah, okay... but does it make sense to have these parameters in the final model structure? It is not used any more and the user cannot comprehend why the parameter is there..

**Comment by Yuri05** [comment]
We have tons of parameters which are not used in the model (e.g. because they belong to a calculation methos which is not used in the given simulation etc.).
We don't remove them, but it would be good to at least mark them as unused (s. the discussion in https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1050)

**Comment by PavelBal** [comment]
OKay, closing
