### ISSUE TITLE
PV BB: assignment of new table formula - strange behavior

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1586]
[Parameter Values.zip](https://github.com/user-attachments/files/17415781/Parameter.Values.zip)

1. Create a new MoBi project and a new module
2. Load the attached PV BB
3. Add a new entry with path `Organism|Liver|Volume`
4. Click on the three dots in the "Formula" column to create a new formula
5. An existing formula is pre-selected and new formula of the same type cannot be created. To create a new formula, "Formula type" must be changed:

![image](https://github.com/user-attachments/assets/edd60346-eae5-4509-b02b-b5c904eccef8)

Expectation: No formula is pre-selected!

Strangely, this does not happen if adding e.g. `foo|bar` as a parameter.

**Comment by SoFiHo05** [comment]
Related to this issue: With a workaround I managed to add an x-Argument formula for a second volume, but it is prefilled based on the previous formula for the same type (e.g. Volume). If the x-argument is the same in both cases, one still needs to go through the drop-down menu and select the x-argument (e.g., maternal age in the example above) again. Otherwise one gets the following error: 
![image](https://github.com/user-attachments/assets/05f61cb4-6e0f-48d1-86de-900a69a4374d)
