### ISSUE TITLE
"Convert to extension module" prompt comes 2 times

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1653]
[01.zip](https://github.com/user-attachments/files/17737573/01.zip)
Commit simulation S1 to building blocks. The prompt below comes 2 times
![grafik](https://github.com/user-attachments/assets/4b691c0c-61fb-4487-84a0-ad453d6cf2d4)

**Comment by Yuri05** [comment]
If I commit to bulding blocks and try to roll back the action in the history, I get the message below and no rollback.
Is it as expected? 
@PavelBal @rwmcintosh @msevestre @benjaperez1983 
![grafik](https://github.com/user-attachments/assets/63227469-06ff-47c0-9a4e-7f3accda6994)

**Comment by PavelBal** [comment]
As S1 is a PK-Sim module, commiting changes to it wold convert it to an extension module, so that's correct. So the issues here  are:

- Promt coming two times. If you click "OK" in the first window but "Cancel" in the second, the module is not converted (and the updated values are not commited)
- Rollback not possible. Not sure it can be fixed, but is definitely an inconvenience for the user.

**Comment by Yuri05** [comment]
ok, I have extracted the 2nd issue into a separate issue: https://github.com/Open-Systems-Pharmacology/MoBi/issues/1657

**Comment by rwmcintosh** [comment]
One prompt for this bb
![image](https://github.com/user-attachments/assets/fb94e53f-d3cb-46db-887c-f850368ea79d)

The other for this bb
![image](https://github.com/user-attachments/assets/79f59cc6-87de-44d1-b718-2373e226491a)

Obviously, we don't want the prompt for the simulation module.
