### ISSUE TITLE
"Events" container is exported every time any container is exported to PKML?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1711]
1. Any PK-Sim simulation -> Send to MoBi
2. Open the Spatial Structures BB and export an organ to PKML, e.g., Bone
3. The `Events` container is co-exported:

```
  <TopContainers>
    <Container id="Jho22agABEe1TrkFzjHNfQ" name="Events" mode="Logical" containerType="Other" />
    <Container id="0b07GbML9ECQdHOecEH9Hg" name="Bone" description="Bone" icon="Bone" mode="Logical" containerType="Organ">
```

Should not be the case.

**Comment by rwmcintosh** [comment]
oh, yeah. That's probably brand new because we are creating a brand new `SpatialStructure` to support the top container.

Because of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2374 we always automatically create the `Events` container any time a spatial structure is generated.

So in this case, we have to remove it because we **don't** want it.
