### ISSUE TITLE
running simulation problem

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/MoBi#177]
Hi,
I built the simple model presented in the MoBi manual (A -> B) but when I run the simulation I get an error message saying: Unable to create simulation. This might be related to the fact that I wasn't able to link the reaction parameter to the reference list. In the manual it says that this is done by dragging but the image is outdated and that option doesn't seem to be there any more. Can you please advise on how to establish that link?

Thanks,
Ahmed.

**Comment by msevestre** [comment]
Can you attach your project? Thanks

**Comment by aelmokadem** [comment]
Thanks for the reply. Here is the project file:
[testmobi.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1317621/testmobi.zip)

**Comment by msevestre** [comment]
Hi @aelmokadem 
The problem is indeed that you have a path in your reaction kinetic that does not point to any existing parameter

![image](https://user-images.githubusercontent.com/1041237/30644339-0fe433c6-9de0-11e7-9c8f-5d6e77bce620.png)

- Remove the entry using the X
- select the parameter K in the tree view 
![image](https://user-images.githubusercontent.com/1041237/30644393-3544619a-9de0-11e7-9445-e030843e481b.png)
- drag the parameter K into the empty space
![image](https://user-images.githubusercontent.com/1041237/30644418-4a39626c-9de0-11e7-9994-01b56299abd2.png)

- you should be good to go
![image](https://user-images.githubusercontent.com/1041237/30644431-5a3f6f1c-9de0-11e7-82c1-58c838a1cf88.png)

Please reopen if you still have issues

**Comment by aelmokadem** [comment]
Thanks Michael. That did solve the problem. Accessing the tree view to drag the parameter was a little tricky though.

**Comment by msevestre** [comment]
@aelmokadem are you referring to screen size (e.g. tree not visible or sthg?)
Yes MoBi is quite demanding. Laptop screen typically too small for some of the UI features
That being said, you can always enter path in formula by hand (which is what you end up doing anyways once you get used to the syntax... this is MUCH faster)

**Comment by aelmokadem** [comment]
Yes I believe it was the screen size. I was only able to see the tree (and the references to add list) when I closed the journal window. As you said, it might be easier just to manually add the path.
