### ISSUE TITLE
Feature wish: Interface for creating neighborhoods

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#326]
Currently, neighborhoods can only be created in the "Diagram"-view of the spatial structure by drag&drop betweem containers. This can be very tedious.
It would be great to have an additional option to create a neighborhood from an interface (called e.g. by a button "New neighborhoods" where the containers to be connected are selected from a list ("choose first neighbor" and "choose second neighbor").

**Comment by msevestre** [comment]
Agreed. The current way of creating neighborhood is not ideal. Also we cannot automate tests at the moment because of that

**Comment by UlrichSi** [comment]
This really is one of our veteran feature requests for the spatial structure workflow, spooking the various used bug tracking systems since many years. 

If this were to be implemented, we might as well think about a concept how to enable editing/changing the neighborhood source and target containers. Which is another veteran request.

**Comment by PavelBal** [comment]
This has been implemented within OSMOSES
