### ISSUE TITLE
Sensitivity analysis for observer

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/MoBi#498]
I want to run a SA on my simulation output in MoBi. 
![grafik](https://user-images.githubusercontent.com/26056951/87804067-a6881b80-c853-11ea-8a3a-48c674f080f3.png)

After selecting the model parameters which are driving the output parameter (N oder time) and running the SA, it seems like I only get an SA on the start value of the respective parameter (Organism|N). The results for tmax also seem implausible given the start time of the simulation. Any reason for this behavior and is there a way to run a SA on the PK parameter of the output parameter over time?
![grafik](https://user-images.githubusercontent.com/26056951/87804538-4cd42100-c854-11ea-94e9-a22b93124a2d.png)

**Comment by msevestre** [comment]
@JanSchlender I am not quite sure I understand what's going on
Anyways you can attach/send me a project so that can reproduce?

**Comment by JanSchlender** [comment]
Here you are

**Comment by Yuri05** [comment]
@JanSchlender 

Ok, it's just because the values of your curve of interest become too high and out of the range.
That's also the reason, why only 45h are displayed (and simulation settings require 72h output).

Thus most calculated PK values (C_max, AUC, ..) are infinity and sensitivity of those values returns NaN.

FYI: OSPSuite performs all calulations using **double precision**. However once the calculation is finished, values are stored using **float precision**. Also PK values are stored using the float precision. Which allows saving values up to [~10^38](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types). 

If you e.g. restrict the simulated time range so that the simulated values do not become Infinity (e.g. set it to 40h), then all sensitivities are properly calculated.

So the problem has nothing to do with observer, just with the values range.

P.S. Not sure what is counted here, but it seems that at 72h the number is higher than the number of atoms on the Earth...

**Comment by msevestre** [comment]
>Not sure what is counted here, but it seems that at 72h the number is higher than the number of atoms on the Earth.

$$ on Jan's bank account?

**Comment by JanSchlender** [comment]
Ok, accepted ;)

> Thus most calculated PK values (C_max, AUC, ..) are infinity and sensitivity of those values returns NaN.

How about the sensitivity calculated for tmax? Since the curve is increasing, I cannot even observe a tmax

**Comment by Yuri05** [comment]
>How about the sensitivity calculated for tmax? Since the curve is increasing, I cannot even observe a tmax 

Don't know why it's not NaN as well... anyway I would not trust it

**Comment by msevestre** [comment]
Well t_max is well defined, even if a curve is increasing. 
It might not make sense, but in an interval [time_min, time_max], there is at least value of time where the concentration is max (in that case time_max).
So while it does not make sense, I understand why it is not NAN
