### ISSUE TITLE
Remove negativeValuesAllowed="0"

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/MoBi#505]
I don't know why this was introduced in the first place, but I vote (or I propose) to remove this "feature" of not allowing negative values.

If the model is set up the way it should be, negative values will not occur for the states where they are not intended. 
If negative values do occur where they shouldn't then you have to debug your model. But producing an error here, really doesn't help much. Maybe a warning could suffice?

**Comment by Yuri05** [comment]
>I don't know why this was introduced in the first place, but I vote (or I propose) to remove this "feature" of not allowing negative values.

It was introduced to avoid modeling errors and detect some numerical problems. It can happen (and in fact it did happened), that simulation results were wrong, but it was overseen by users, because they e.g. looked on plasma curves only.
I am strictly against disabling this feature.

>Maybe a warning could suffice?

Warnings are usually overseen as well by the most users. Also, other (uncritical) warnings could occur. In such a case "negative values" warning could also easily get lost among others (unless we define critical/uncritical warnings or so)

At the moment user can disable this feature in MoBi by allowing negative values for some variables. Also in the R-Toolbox by adjusting `SimulationRunOptions `when running a simulation.

We could add `NegativeValuesAllowed `as one of solver settings, however this might produce confusions with e.g. per Variable setting in MoBi,

**Comment by PavelBal** [comment]
I see the point in having this check.

On the other hand, I very often cannot run the simulations because of this. The annoying part is that even molecules that were not administered or produced (so should be just 0 everywhere) become negative rather often. It usually happens in compartments where the molecules are subjects to active transporters - so the active transporters seem to be very unstable.

**Comment by StephanSchaller** [comment]
If you can disable this feature (e.g. with `SimulationRunOptions` in R), that's fine. I didn't know this.
Maybe also have a global setting for this in MoBi?

Also, can you return the timepoint in the error message?

Also, the output that is currently returned as the one causing the issue might not be the one that **first** crosses the "zero line". How is the output selected?

**Comment by Yuri05** [comment]
>The annoying part is that even molecules that were not administered or produced (so should be just 0 everywhere) become negative rather often. It usually happens in compartments where the molecules are subjects to active transporters - so the active transporters seem to be very unstable.

When you have this again: could you attach your model?

>Maybe also have a global setting for this in MoBi?

You could disable "Negative values allowed" for ALL molecules in MSV - this would correspond to disabling the feature

>Also, can you return the timepoint in the error message?

Can be easily done. Please create an issue for this (in OSPSuite.SimModel).

>Also, the output that is currently returned as the one causing the issue might not be the one that first crosses the "zero line". How is the output selected?

~~You see ALL outputs which became negative. However you don't see which of them became neagive first indeed.~~
You are right: only one of negative outputs is shown, which is actually a small bug in the code. Please create an issue for this (in OSPSuite.SimModel).

https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/08fb0d56cc0ca017f0491ff615267ace2f69d07a/src/OSPSuite.SimModelNative/src/SimulationTask.cpp#L194-L219

**Comment by Yuri05** [comment]
closing in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/119
