### ISSUE TITLE
Recreating a PK-Sim simulation with proteins creates unnecessary containers

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#519]
If I export a simulation which contains proteins from PK-Sim to MoBi and recreate in MoBi, unnecessary empty molecule properties containers are created on organ level.
E.g. originally exported simulation looks like this (molecule properties for CYP3A4 only on **compartment** level, which is correct):
![grafik](https://user-images.githubusercontent.com/25061876/96997925-f8b39980-1532-11eb-9946-2bf1b0732745.png)
Creating new simulation from existing building blocks in MoBi produces empty CYP3A4-container on organ level:
![grafik](https://user-images.githubusercontent.com/25061876/96998013-154fd180-1533-11eb-9aaf-880099289f0e.png)

If such a simulation is then exported back to PK-Sim: editing of relative expressions crashes
![grafik](https://user-images.githubusercontent.com/25061876/96998228-61027b00-1533-11eb-9c3f-890b0f1c824b.png)
(I guess due to normalization, which tries to find relExp_Norm parameter in ALL CYP3A4-containers, which crashes then for those wrongly inserted empty containers.

**Comment by msevestre** [comment]
Well well...it took me some times but it seems to be `by design`
In PKSim, observers are never ForAll. However, when we export to Mobi, some observers are set explicitly to ForAll=True
```
  public static IReadOnlyCollection<string> MoBiForAll => new[]
            {CONCENTRATION_IN_CONTAINER, FRACTION_EXCRETED_TO_URINE, TISSUE, PLASMA_PERIPHERAL_VENOUS_BLOOD, PLASMA_UNBOUND_PERIPHERAL_VENOUS_BLOOD};

```

One of them is Tissue
![image](https://user-images.githubusercontent.com/1041237/110997592-a214f380-834b-11eb-8d05-6303ddfc553f.png)

and that's why it is showing up here

I feel that ForAll should not apply to non floating molecule 

@Yuri05 @PavelBal @StephanSchallerThoughts?

**Comment by msevestre** [comment]
but then we have another difference

![image](https://user-images.githubusercontent.com/1041237/110999284-25cfdf80-834e-11eb-8c7e-9e5f4bec9582.png)


hum... Not sure how to solve this unless we remove this difference of behavior between mobi and pksim (e..g observers are not set to ForAll=True)

**Comment by Yuri05** [comment]
>I feel that ForAll should not apply to non floating molecule

no real opinion on this...

**Comment by PavelBal** [comment]
>In PKSim, observers are never ForAll. However, when we export to Mobi, some observers are set explicitly to ForAll=True

Why is it done this way? I don't see a reason why I would like to have more observers in MoBi than in PK-Sim...

> I feel that ForAll should not apply to non floating molecule

I am not sure as I cannot think of all the implications right now...

**Comment by msevestre** [comment]
>Why is it done this way? I don't see a reason why I would like to have more observers in MoBi than in PK-Sim...

Probably because if you add a molecule, then suddenly none of the standard observers are available for this molecule because you forgot to add it in the MoleculeList. 

So I can see why this was done like this. The only "clean" way to get the same is to remove this function in PKSim. Then, as a MoBi user, you would have to remember to add your new molecule in this list

Not sure what is best to be honest

>I feel that ForAll should not apply to non floating molecule

This has now the side effects that Concentration Observer is not available for Enzyme etc..

**Comment by PavelBal** [comment]
> Probably because if you add a molecule, then suddenly none of the standard observers are available for this molecule because you forgot to add it in the MoleculeList.

You mean if you add a molecule in MoBi? I don't see a big problem in manually adding the molecule into the list then... Until for this version.

In general, we also had a discussion about adding non-floating molecules to passive transports, and when this will be done we should make sure that the behavior on include/exclude/forAll is the same in passive transports and observers.

**Comment by msevestre** [comment]
So the only way around this @Yuri05 , is to remove 
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/233d312adc3df504cc8f9c7367a16f4c9c68603a/src/PKSim.Infrastructure/Services/MoBiExportTask.cs#L146

I think that removing it, even though it is somewhat of a breaking change, is what we should do because it ensures that the same building blocks are producing the same outputs

**Comment by msevestre** [comment]
ok what do we do here? @Yuri05 ?
