### ISSUE TITLE
can not see optional references projects

### ISSUE THREAD

**Issue by tztz117** [Open-Systems-Pharmacology/MoBi#580]
I am following Kuepfer's paper to add the "CIP" parameter, however, after checking parameter is state variable, in the expanded I can not expand any more to be able to see the possible referenced objects list, as shown in the picture, is there a way to be able to see it so i can drag parameter to the left field? thanks very much
![possible reference objects](https://user-images.githubusercontent.com/86744277/125026718-2b66d900-e053-11eb-8e73-2b20cbe1fbf6.JPG)

**Comment by Yuri05** [comment]
seems your window size is just too small, so that the referenced objects are not visible.
You should either increase the window size or collapse the panels **Properties** and I**nitial Value** (click on **^** )
![grafik](https://user-images.githubusercontent.com/25061876/125048519-51ff3100-e0a0-11eb-967a-f4b02a233704.png)

**Comment by tztz117** [comment]
Thank you very much, Juri!
