### ISSUE TITLE
Add new organ (e.g. tumor) sub-compartment automatically

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/MoBi#813]
Feature wish: In MoBi, adding a new compartment (e.g. tumor) within an organ, one needs to go through a list of adjustments and is not that straight forward (and error prone).

Would it be possible to make it a MoBi standard option and create one on a click basis?

@Christoph27

**Comment by Yuri05** [comment]
S. the major discussion regarding this issue here: https://github.com/Open-Systems-Pharmacology/Forum/discussions/1180

Also related to the following issues:
* https://github.com/Open-Systems-Pharmacology/OSMOSES/issues/4
* https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/378
* https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/603
* https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/884
* https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1347

@michblock FYI

**Comment by PavelBal** [comment]
I think the current workflow in v12 is already good enough. Feel free to re-open if you have more suggestions.
